//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videobutik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoStoreEntities : DbContext
    {
        public VideoStoreEntities()
            : base("name=VideoStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Moviegenre> Moviegenre { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
